jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs  # Make sure this points to where your Jekyll files are
          destination: ./docs/_site
